name: Android Appium E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm ci
          npm run apk:fetch

      - name: Run on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel_6
          disable-animations: true
          force-avd-creation: true
          emulator-options: -no-window -no-boot-anim -noaudio -no-snapshot -no-snapshot-load -no-snapshot-save -wipe-data -gpu swiftshader_indirect -camera-back none -camera-front none -skip-adb-auth
          script: |
            set +e; adb kill-server || true; adb start-server; adb devices || true; ANDROID_SERIAL=${ANDROID_SERIAL:-emulator-5554}; ONLINE=0; i=1; while [ $i -le 60 ]; do STATE=$(adb -s "$ANDROID_SERIAL" get-state 2>/dev/null | tr -d '\r'); if [ "$STATE" = "device" ]; then echo "Emulator is online"; ONLINE=1; break; fi; echo "Waiting for emulator to come online... ($i/60)"; i=$((i+1)); sleep 5; done; if [ "$ONLINE" -ne 1 ]; then echo "Emulator failed to come online within 5 minutes"; exit 1; fi; BOOTED=0; i=1; while [ $i -le 120 ]; do BOOT=$(adb -s "$ANDROID_SERIAL" shell getprop sys.boot_completed 2>/dev/null | tr -d '\r'); if [ "$BOOT" = "1" ]; then echo "Emulator boot completed"; BOOTED=1; break; fi; echo "Waiting for sys.boot_completed... ($i/120)"; i=$((i+1)); sleep 5; done; if [ "$BOOTED" -ne 1 ]; then echo "Emulator failed to fully boot within 10 minutes"; adb -s "$ANDROID_SERIAL" shell getprop sys.boot_completed || true; exit 1; fi; adb -s "$ANDROID_SERIAL" shell settings put global window_animation_scale 0 || true; adb -s "$ANDROID_SERIAL" shell settings put global transition_animation_scale 0 || true; adb -s "$ANDROID_SERIAL" shell settings put global animator_duration_scale 0 || true; adb -s "$ANDROID_SERIAL" shell input keyevent 82 || true; npm test
